# Generated by Django 4.1.2 on 2022-10-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_documents_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_documents',
            new_name='Additional_document',
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
